# Generated by Django 4.0.3 on 2022-03-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_article_resume_alter_article_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='miniature',
            field=models.ImageField(height_field=200, null=True, upload_to='', width_field=200),
        ),
    ]
